#!/usr/bin/bash

# some more ls aliases
alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# mv, rm, cp
alias mv='mv -v'
alias rm='rm -v'
alias cp='cp -v'

alias hosts='sudo $EDITOR /etc/hosts'

# Recursively delete `.DS_Store` files
alias diskspace_report="df -P -kHl"

# File size
alias fs="stat -f \"%z bytes\""
alias ungz="gunzip -k"