#!/bin/bash
# file is shared between bash and fish

# vim as default
export EDITOR="vim"

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"

#Prefer US English and use UTF-8
#export LC_ALL="en_US.UTF-8"
#export LANG="en_US"

# highlighting inside manpages and elsewhere
export LESS_TERMCAP_mb=$(printf '\e[01;31m')													# enter blinking mode – red
export LESS_TERMCAP_md=$(printf '\e[01;35m')													# enter double-bright mode – bold, magenta
export LESS_TERMCAP_me=$(printf '\e[0m')															# turn off all appearance modes (mb, md, so, us)
export LESS_TERMCAP_se=$(printf '\e[0m')															# leave standout mode
export LESS_TERMCAP_so=$(printf '\e[01;33m')													# enter standout mode – yellow
export LESS_TERMCAP_ue=$(printf '\e[0m')															# leave underline mode
export LESS_TERMCAP_us=$(printf '\e[04;36m')													# enter underline mode – cyan

## HISTORY settings... 
# Use standard ISO 8601 timestamp
# %F equivalent to %Y-%m-%d
# %T equivalent to %H:%M:%S (24-hours format)
export HISTTIMEFORMAT='%F %T '

# keep history up to date, across sessions, in realtime
#  http://unix.stackexchange.com/a/48113
export HISTCONTROL="ignoredups"       # no duplicate entries, but keep space-prefixed commands. (bash-sensible uses "erasedups:ignoreboth" but i think i validated this already?)
# here's the popularity amonngst other-peoples-dotfiles... (cmd: ag --nogroup --noheading --nofilename --hidden -o "HISTCONTROL.*" |  grep -E -o "(ignore|erase)[a-z:]*" | sort | uniq -c | sort -r)
#      5 ignoreboth
#      4 ignoredups
#      2 erasedups:ignoreboth
#      1 ignorespace:erasedups
#      1 ignoredups:erasedups
#      1 erasedups
export HISTSIZE=2000                            # big big history (default is 500)
export HISTFILESIZE=$HISTSIZE                   # big big history

# Don't record some commands
export HISTIGNORE="&:[ ]*:exit:ls:bg:fg:history:clear"

# Save and reload the history after each command finishes. Also look for any conflicting prompt_command definitions!!
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

# fzf should be populated via `fd` which is the fastest file/dir finder. (respects gitignore, etc)
# note.. `fd` seems faster than `ag`.. but if i wanted to use `ag` this is good: command ag --files-with-matches --filename-pattern ""
# fd > 8.1 got slower. https://github.com/sharkdp/fd/issues/1131
#    so.. here's the install for the last fast one: CARGO_NET_GIT_FETCH_WITH_CLI=true cargo install --vers 8.1.1 fd-find
# To do a fzf including hidden/ignord files.. 'fd --unrestricted'
export FZF_DEFAULT_COMMAND='fd'
export FZF_CTRL_T_COMMAND='fd'
export FZF_CTRL_T_OPTS="--preview 'bat -n --color=always {} 2>/dev/null || tree -C {}'"

